### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by fbongcam** [vidstige/jadb#153]
```
java.io.EOFException
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:210)
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:179)
        at jadb@1.2.1/se.vidstige.jadb.SyncTransport.readString(SyncTransport.java:50)
        at jadb@1.2.1/se.vidstige.jadb.SyncTransport.verifyStatus(SyncTransport.java:33)
        at jadb@1.2.1/se.vidstige.jadb.JadbDevice.push(JadbDevice.java:196)
        at jadb@1.2.1/se.vidstige.jadb.JadbDevice.push(JadbDevice.java:202)
```

I keep getting this exception while pushing files to device. It seems to happen after a certain amount of bytes has been transfered but I'm not sure. It's so random and happens almost every time when the process has to run over 5-10 seconds. Either when running the push method in a for loop to push multiple files, or when a larger single file is being transfered. Connection just dies for some reason.

**Comment by fbongcam** [comment]
It seems that having Android Studio running at the same time causes the connection to disconnect and reconnect. So it's not an issue related to the library.
